### ISSUE TITLE
fcntl is breaking burr server on Windows

### ISSUE THREAD

**Issue by zenfiric** [DAGWorks-Inc/burr#235]
`fnctl` does not work on Windows, for it can be used `msvcrt`.
burr==0.22.0 breaks for that reason.

## Stack Traces

     ...burr\tracking\client.py", line 3, in <module>
     import fcntl
     ModuleNotFoundError: No module named 'fcntl'

## Library & System Information
The burr server is breaking since 0.22.0, after #225

**Comment by elijahbenizzy** [comment]
Thanks for flagging! This is due to the fcntl locking for parallel stuff. I'd rather it fail later on than earlier, as it's not essential. That said, will have to flag and fix later. 

In the meanwhile, fix is (hopefully) here: https://github.com/DAGWorks-Inc/burr/pull/236. `burr[learn]=="0.22.1rc0"`

**Comment by elijahbenizzy** [comment]
This is fixed! Released in `0.22.1`
